# Generated by Django 4.0 on 2021-12-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.TextField()),
                ('SECOND_NAME', models.TextField()),
                ('PATRON_NAME', models.TextField()),
                ('PHONE_NUMBER', models.CharField(max_length=14)),
            ],
        ),
    ]
