# Generated by Django 4.0 on 2021-12-21 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars_info',
            fields=[
                ('CAR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CAR_BRAND', models.TextField()),
                ('CAR_MODEL', models.TextField()),
                ('CAR_YEAR', models.IntegerField()),
                ('CAR_ENGINE', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('SUPPLIER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SUPPLIER_NAME', models.TextField()),
                ('CONTACT_PHONE', models.TextField()),
                ('CONTACT_MAIL', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('WORKER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.TextField()),
                ('SECOND_NAME', models.TextField()),
                ('PATRON_NAME', models.TextField()),
                ('WORK_TYPE', models.IntegerField()),
                ('POSITION', models.TextField()),
                ('WAGE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='works_list',
            fields=[
                ('WORK_TYPE', models.IntegerField()),
                ('TYPE_NAME', models.TextField()),
                ('WORK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('WORK_NAME', models.TextField()),
                ('PART_NAME', models.TextField()),
                ('WORK_COST', models.IntegerField()),
                ('WARRANTY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pending',
            fields=[
                ('TICKET_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DATE', models.DateField()),
                ('TIME', models.TimeField()),
                ('CAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.cars_info')),
                ('CUSTOMER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.customer')),
                ('WORK_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.works_list')),
            ],
        ),
        migrations.CreateModel(
            name='parts',
            fields=[
                ('PART_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PART_NAME', models.TextField()),
                ('QUANTITY', models.IntegerField()),
                ('PART_COST', models.IntegerField()),
                ('CAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.cars_info')),
            ],
        ),
        migrations.CreateModel(
            name='finished_works',
            fields=[
                ('TICKET_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DATE', models.DateField(verbose_name=datetime.date(2021, 12, 21))),
                ('COST', models.IntegerField()),
                ('WARRANTY', models.IntegerField()),
                ('CAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.cars_info')),
                ('CUSTOMER_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.customer')),
                ('WORKER_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.workers')),
                ('WORK_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.works_list')),
            ],
        ),
        migrations.CreateModel(
            name='bought_parts',
            fields=[
                ('PART_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PART_NAME', models.TextField()),
                ('QUANTITY', models.IntegerField()),
                ('PART_COST', models.IntegerField()),
                ('DATE', models.DateField(verbose_name=datetime.date(2021, 12, 21))),
                ('CAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.cars_info')),
                ('SUPPLIER_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.suppliers')),
            ],
        ),
    ]
