# Generated by Django 4.0 on 2021-12-22 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_cars_info_suppliers_workers_works_list_pending_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought_parts',
            name='DATE',
            field=models.DateField(verbose_name=datetime.date(2021, 12, 22)),
        ),
        migrations.AlterField(
            model_name='finished_works',
            name='DATE',
            field=models.DateField(verbose_name=datetime.date(2021, 12, 22)),
        ),
    ]
