# Generated by Django 4.0 on 2021-12-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_bought_parts_date_alter_finished_works_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='WORK_TYPE',
        ),
        migrations.AddField(
            model_name='workers',
            name='TYPE_NAME',
            field=models.TextField(null=True),
        ),
    ]
