# Generated by Django 4.0 on 2021-12-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_workers_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='TYPE_NAME',
            field=models.TextField(null=True),
        ),
    ]
