# Generated by Django 4.0 on 2021-12-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_workers_worker_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_displayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAR_BRAND', models.TextField()),
                ('CAR_MODEL', models.TextField()),
                ('CAR_YEAR', models.IntegerField()),
                ('CAR_ENGINE', models.TextField()),
                ('PART_NAME', models.TextField()),
                ('QUANTITY', models.IntegerField()),
                ('PART_COST', models.IntegerField()),
            ],
            options={
                'db_table': 'managed_display_stock',
                'managed': False,
            },
        ),
    ]
