# Generated by Django 4.0 on 2021-12-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_stock_displayer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock_displayer',
            table='manager_display_stock',
        ),
    ]
