# Generated by Django 4.0 on 2021-12-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_stock_displayer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought_parts',
            name='CAR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.cars_info'),
        ),
    ]
