# Generated by Django 4.0 on 2021-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_bought_parts_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought_parts',
            name='DATE',
            field=models.DateField(auto_now_add=True),
        ),
    ]
