# Generated by Django 4.0 on 2021-12-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_bought_parts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_works',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finished_works',
            name='TICKET_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.pending'),
        ),
    ]
