# Generated by Django 4.0 on 2021-12-23 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_bought_parts_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_works',
            name='DATE',
            field=models.DateField(verbose_name=datetime.date(2021, 12, 23)),
        ),
    ]
