# Generated by Django 4.0 on 2021-12-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_finished_works_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='DATE',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pending',
            name='TIME',
            field=models.TextField(),
        ),
    ]
