# Generated by Django 4.0 on 2021-12-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_pending_date_alter_pending_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pending',
            old_name='DATE',
            new_name='WDATE',
        ),
        migrations.RenameField(
            model_name='pending',
            old_name='TIME',
            new_name='WTIME',
        ),
    ]
