# Generated by Django 4.0 on 2021-12-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_rename_date_pending_wdate_rename_time_pending_wtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='pending_displayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TICKET_ID', models.IntegerField()),
                ('WDATE', models.TextField()),
                ('WTIME', models.TextField()),
                ('WORK_NAME', models.TextField()),
                ('SECOND_NAME', models.TextField()),
                ('FIRST_NAME', models.TextField()),
                ('CAR_BRAND', models.TextField()),
                ('CAR_MODEL', models.TextField()),
            ],
            options={
                'db_table': 'manager_pending_displayer',
                'managed': False,
            },
        ),
    ]
