# Generated by Django 4.0 on 2021-12-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_pending_displayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='IS_FINISHED',
            field=models.IntegerField(default=0),
        ),
    ]
