# Generated by Django 4.0 on 2021-12-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_remove_pending_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='IS_FINISHED',
            field=models.IntegerField(default=0),
        ),
    ]
