# Generated by Django 4.0 on 2021-12-27 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_pending_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='finished_displayer',
            fields=[
                ('TICKET_ID', models.AutoField(primary_key=True, serialize=False)),
                ('WDATE', models.TextField()),
                ('WTIME', models.TextField()),
                ('WORK_NAME', models.TextField()),
                ('SECOND_NAME', models.TextField()),
                ('FIRST_NAME', models.TextField()),
                ('CAR_BRAND', models.TextField()),
                ('CAR_MODEL', models.TextField()),
            ],
            options={
                'db_table': 'manager_finished_displayer',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='finished_works',
            name='DATE',
            field=models.DateField(verbose_name=datetime.date(2021, 12, 27)),
        ),
    ]
